import type { PipelineStage, SourceConfig } from "@/lib/types";

export const sources: SourceConfig[] = [
  {
    id: "dcinside",
    name: "DCInside",
    url: "https://www.dcinside.com/",
    kind: "community",
    category: "general trends",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 72,
    status: "active",
    notes: "Large volume, fast trend detection, requires board-level targeting later.",
  },
  {
    id: "mlbpark",
    name: "MLBPark",
    url: "https://mlbpark.donga.com/mp/b.php?b=bullpen",
    kind: "forum",
    category: "community discussions",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 67,
    status: "active",
    notes: "Useful for lifestyle, sports, and current-topic spikes.",
  },
  {
    id: "fmkorea",
    name: "FMKorea",
    url: "https://www.fmkorea.com/best",
    kind: "community",
    category: "viral topics",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 75,
    status: "active",
    notes: "High volume and meme diffusion, needs aggressive deduplication.",
  },
  {
    id: "dogdrip",
    name: "Dogdrip",
    url: "https://www.dogdrip.net/?mid=dogdrip&sort_index=popular",
    kind: "community",
    category: "viral community",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 70,
    status: "active",
    notes: "Popular-post signal source with broad issue and meme coverage.",
  },
  {
    id: "theqoo",
    name: "theqoo",
    url: "https://theqoo.net/",
    kind: "community",
    category: "pop culture",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 71,
    status: "active",
    notes: "Strong signal source for fandom, entertainment, and consumer topics.",
  },
  {
    id: "bobaedream-best",
    name: "Bobaedream Best",
    url: "https://www.bobaedream.co.kr/list?code=best",
    kind: "aggregation",
    category: "best posts",
    region: "KR",
    language: "ko",
    crawlIntervalHours: 24,
    trustScore: 64,
    status: "active",
    notes: "Opinion-heavy source. Good for urgency and controversy cues.",
  },
];

export const pipelineStages: PipelineStage[] = [
  {
    id: "source-registry",
    name: "Source Registry",
    state: "ready",
    summary: "Registered source inventory with crawl cadence, trust score, and category.",
    output: "6 active Korean community sources",
  },
  {
    id: "doc-ingestion",
    name: "Document Ingestion",
    state: "next",
    summary: "Fetch board/list pages, normalize HTML, and persist raw snapshots for parsing.",
    output: "Next: crawler adapters per source",
  },
  {
    id: "keyword-extraction",
    name: "Primary Keyword Extraction",
    state: "next",
    summary: "Extract Korean noun phrases and frequency-weighted trend candidates.",
    output: "Next: scored keyword candidates",
  },
  {
    id: "suggest-expansion",
    name: "Suggest Expansion",
    state: "next",
    summary: "Expand primary keywords through Google Suggest with caching and backoff.",
    output: "Next: secondary keyword graph",
  },
  {
    id: "analysis-generation",
    name: "GPT Analysis",
    state: "next",
    summary: "Generate intent, related terms, FAQ, and snippet drafts for new keywords only.",
    output: "Next: analysis JSON per keyword",
  },
  {
    id: "page-generation",
    name: "SERP Page Generation",
    state: "next",
    summary: "Materialize keyword pages, metadata, internal links, and sitemap updates.",
    output: "Next: public keyword routes",
  },
];
